/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package airlinemanagement;

/**
 *
 * @author ADMIN88
 */
public class ChatItem extends javax.swing.JPanel {

    /**
     * Creates new form ChatItem
     */
    private String username;
    public ChatItem(String name, String lastMessage) {
        initComponents();
        setInfo(name, lastMessage);
        setPreferredSize(new java.awt.Dimension(250, 60));
        setMinimumSize(new java.awt.Dimension(200, 50));
        setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
 
        setAlignmentX(LEFT_ALIGNMENT);
        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY));
    }
    public void setInfo(String name, String lastMessage) {
        this.username = name;
        jLabel1.setText(name);
        lastMessageJlabel.setText(lastMessage);
    }
    public void addClickEvent(java.awt.event.MouseAdapter adapter) {
    this.addMouseListener(adapter);

    jLabel1.addMouseListener(adapter);
    lastMessageJlabel.addMouseListener(adapter);
}
    public String getUserName() {
        return username;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lastMessageJlabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(9999, 50));
        setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        lastMessageJlabel.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lastMessageJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastMessageJlabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastMessageJlabel;
    // End of variables declaration//GEN-END:variables
}
