/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinemanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import javax.swing.JTable;

/**
 *
 * @author ADMIN88
 */
public class staffForm extends javax.swing.JFrame {

    /**
     * Creates new form staffForm
     */
    public staffForm() {
        initComponents();
        DisplayStaffs();
        deleteSearchBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1 = null;
    Statement St = null, St1 = null;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StaffTable1 = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StaffPhoneTb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StaffNameTb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StaffAddressTb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        StaffNatCb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        StaffGenCb = new javax.swing.JComboBox<>();
        BackBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        PasswordField = new javax.swing.JPasswordField();
        roleCb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        deleteSearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveBtn.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(204, 0, 51));
        SaveBtn.setText("Save");
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        StaffTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Staff name", "Nationality", "Gender", "Phone", "Address"
            }
        ));
        StaffTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StaffTable1);

        DeleteBtn.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(204, 0, 51));
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Airline Management");

        jLabel3.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Manage staff");

        StaffPhoneTb.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        StaffPhoneTb.setForeground(new java.awt.Color(204, 0, 51));
        StaffPhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffPhoneTbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Staff name");

        StaffNameTb.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        StaffNameTb.setForeground(new java.awt.Color(204, 0, 0));
        StaffNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffNameTbActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Nationality");

        StaffAddressTb.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        StaffAddressTb.setForeground(new java.awt.Color(204, 0, 51));
        StaffAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffAddressTbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Address");

        StaffNatCb.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        StaffNatCb.setForeground(new java.awt.Color(204, 0, 0));
        StaffNatCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viet Nam", "India", "China", "Russia" }));
        StaffNatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffNatCbActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Password ");

        StaffGenCb.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        StaffGenCb.setForeground(new java.awt.Color(204, 0, 0));
        StaffGenCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));

        BackBtn.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(204, 0, 51));
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("VNI-Book", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Staff List");

        jLabel8.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Gender");

        jLabel11.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Phone");

        jLabel12.setFont(new java.awt.Font("VNI-Book", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("confirm password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        roleCb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roleCb.setForeground(new java.awt.Color(204, 0, 0));
        roleCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Admin", " ", " " }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Role");

        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(102, 102, 102));
        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteSearchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteSearchBtn.setForeground(new java.awt.Color(102, 102, 102));
        deleteSearchBtn.setText("Delete search");
        deleteSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSearchBtnMouseClicked(evt);
            }
        });
        deleteSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(roleCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(StaffGenCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(StaffNatCb, 0, 233, Short.MAX_VALUE)
                                                    .addComponent(StaffNameTb)
                                                    .addComponent(StaffAddressTb)
                                                    .addComponent(StaffPhoneTb)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteSearchBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(308, 308, 308))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(276, 276, 276))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(StaffNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StaffNatCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StaffGenCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(StaffAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(StaffPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(roleCb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveBtn)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackBtn)))
                    .addComponent(jScrollPane2))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void DisplayStaffs() {
        try {
            Con = DBConnection.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM users");
            StaffTable1.setModel(DbUtils.resultSetToTableModel(Rs));
            StaffTable1.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {

                    // Chuyển nội dung hiển thị thành dấu *
                    if (value != null) {
                        value = "********";
                        // Hoặc: value = "•".repeat(value.toString().length()); (Java 11+)
                    }

                    return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                }
            });
        } catch (Exception e) {
        }
    }

    private void Clear() {
        StaffNameTb.setText("");
        StaffAddressTb.setText("");
        PasswordField.setText("");
        ConfirmPasswordField.setText("");
        StaffPhoneTb.setText("");
        StaffGenCb.setSelectedIndex(-1);
        StaffGenCb.setSelectedIndex(-1);
    }
    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        if (!PasswordField.getText().equals(ConfirmPasswordField.getText())) {
            JOptionPane.showMessageDialog(null, "Password is not the same with confirmed password !");
            return;
        }
        if (Key != 0) {
            try {
                //CountPassengers();
                Con = DBConnection.getConnection();
                String Query = "Update users set username=?, password=?, isAdmin =?,nationality=?, gender=?, address=?, phone=? where id=?";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setInt(8, Key);
                Add.setString(1, StaffNameTb.getText());
                Add.setString(2, PasswordField.getText());
                if (roleCb.getSelectedItem().toString().equals("Admin")) {
                    Add.setInt(3, 1);
                } else {
                    Add.setInt(3, 0);
                }
                Add.setString(4, StaffNatCb.getSelectedItem().toString());
                Add.setString(5, StaffGenCb.getSelectedItem().toString());
                Add.setString(6, StaffAddressTb.getText());
                Add.setString(7, StaffPhoneTb.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Staff Updated");
                Con.close();
                DisplayStaffs();
                Clear();
                Key = 0;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else if (StaffNameTb.getText().isEmpty() || PasswordField.getText().isEmpty() || StaffAddressTb.getText().isEmpty() || StaffPhoneTb.getText().isEmpty() || StaffGenCb.getSelectedIndex() == -1 || StaffNatCb.getSelectedIndex() == -1 || roleCb.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                Con = DBConnection.getConnection();
                PreparedStatement Add = Con.prepareStatement("insert into users (username, password, isAdmin, nationality, gender, address, phone) VALUES (?, ?, ?, ?, ?, ?, ?)");;
                Add.setString(1, StaffNameTb.getText());
                Add.setString(2, PasswordField.getText());
                Add.setInt(3, 0);
                Add.setString(4, StaffNatCb.getSelectedItem().toString());
                Add.setString(5, StaffGenCb.getSelectedItem().toString());
                Add.setString(6, StaffAddressTb.getText());
                Add.setString(7, StaffPhoneTb.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Staff Added");
                Con.close();
                DisplayStaffs();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Username or Phone Number all ready exits");
            }
        }
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed
    int Key = 0;
    private void StaffTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) StaffTable1.getModel();
        int MyIndex = StaffTable1.getSelectedRow(); // Lưu ý: trong ảnh là .getSelectedRow thiếu ()
        Key = Integer.parseInt(model.getValueAt(MyIndex, 0).toString());
        StaffNameTb.setText(model.getValueAt(MyIndex, 1).toString());
        PasswordField.setText(model.getValueAt(MyIndex, 2).toString());
        ConfirmPasswordField.setText(model.getValueAt(MyIndex, 2).toString());
        if (Integer.valueOf(model.getValueAt(MyIndex, 3).toString()) == 1) {
            roleCb.setSelectedItem("Admin");
        } else {
            roleCb.setSelectedItem("Staff");
        }
        StaffNatCb.setSelectedItem(model.getValueAt(MyIndex, 4).toString());
        StaffGenCb.setSelectedItem(model.getValueAt(MyIndex, 5).toString());
        StaffAddressTb.setText(model.getValueAt(MyIndex, 6).toString());
        StaffPhoneTb.setText(model.getValueAt(MyIndex, 7).toString());
    }//GEN-LAST:event_StaffTable1MouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        if (Key == 0) {
            JOptionPane.showMessageDialog(this, "Select a staff to delete");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Xóa nhân viên này sẽ xóa toàn bộ tin nhắn và hội thoại liên quan. Bạn chắc chứ?",
                    "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Con = DBConnection.getConnection();
                    Con.setAutoCommit(false); // Bắt đầu Transaction

                    // 1. Xóa tin nhắn thuộc về các hội thoại của User này
                    // Bảng 'messages' tham chiếu 'conversations'
                    String delMessages = "DELETE FROM messages WHERE conversation_id IN "
                            + "(SELECT id FROM conversations WHERE user1_id = ? OR user2_id = ?)";
                    java.sql.PreparedStatement ps1 = Con.prepareStatement(delMessages);
                    ps1.setInt(1, Key);
                    ps1.setInt(2, Key);
                    ps1.executeUpdate();

                    // 2. Xóa các hội thoại của User này
                    // Bảng 'conversations' tham chiếu 'users'
                    String delConvs = "DELETE FROM conversations WHERE user1_id = ? OR user2_id = ?";
                    java.sql.PreparedStatement ps2 = Con.prepareStatement(delConvs);
                    ps2.setInt(1, Key);
                    ps2.setInt(2, Key);
                    ps2.executeUpdate();

                    // 3. Cuối cùng mới xóa User trong bảng 'users'
                    String delUser = "DELETE FROM users WHERE id = ?";
                    java.sql.PreparedStatement ps3 = Con.prepareStatement(delUser);
                    ps3.setInt(1, Key);
                    ps3.executeUpdate();

                    Con.commit(); // Hoàn tất quá trình xóa sạch dữ liệu

                    JOptionPane.showMessageDialog(this, "Staff and all related data deleted");
                    DisplayStaffs();
                    Clear();
                    Key = 0;
                } catch (Exception e) {
                    try {
                        if (Con != null) {
                            Con.rollback(); // Nếu lỗi thì khôi phục lại dữ liệu
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                } finally {
                    try {
                        Con.setAutoCommit(true);
                    } catch (Exception e) {
                    }
                }
            }
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void StaffPhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffPhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffPhoneTbActionPerformed

    private void StaffNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffNameTbActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void StaffAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffAddressTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffAddressTbActionPerformed

    private void StaffNatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffNatCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffNatCbActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
        try {
            String searchQuerry = SearchTextField.getText();
            Con = DBConnection.getConnection();
            String query = "SELECT * FROM users WHERE username LIKE ?";
            PreparedStatement St = Con.prepareStatement(query);
            St.setString(1, "%" + searchQuerry + "%");
            Rs = St.executeQuery();
            StaffTable1.setModel(DbUtils.resultSetToTableModel(Rs));
            StaffTable1.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {

                    // Chuyển nội dung hiển thị thành dấu *
                    if (value != null) {
                        value = "********";
                        // Hoặc: value = "•".repeat(value.toString().length()); (Java 11+)
                    }

                    return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                }
            });
        } catch (Exception e) {
            System.out.println("co loi" + e);
        } finally {
            deleteSearchBtn.setVisible(true);
        }
    }//GEN-LAST:event_searchBtnMouseClicked

    private void deleteSearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSearchBtnMouseClicked
        // TODO add your handling code here:
        SearchTextField.setText("");
        DisplayStaffs();
        deleteSearchBtn.setVisible(false);
    }//GEN-LAST:event_deleteSearchBtnMouseClicked

    private void deleteSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSearchBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JTextField StaffAddressTb;
    private javax.swing.JComboBox<String> StaffGenCb;
    private javax.swing.JTextField StaffNameTb;
    private javax.swing.JComboBox<String> StaffNatCb;
    private javax.swing.JTextField StaffPhoneTb;
    private javax.swing.JTable StaffTable1;
    private javax.swing.JButton deleteSearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> roleCb;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
